/** Auto-generated from api.ozonexpress.ma/cities — exact OzonExpress NAME. */
export type OzoneCity = { id: number; name: string; ref: string };

export const OZONE_CITIES: OzoneCity[] = [
  { id: 2073, name: "aazayeb-chefchaouen", ref: "aazayeb" },
  { id: 2258, name: "Abteh-tantan", ref: "abteh" },
  { id: 1610, name: "Afourar - Beni-Mellal", ref: "Afourar" },
  { id: 2028, name: "AFRA-nador", ref: "afra" },
  { id: 37, name: "Agadir", ref: "AGA" },
  { id: 1844, name: "Agafay", ref: "Agafay" },
  { id: 2130, name: "agdz", ref: "agd" },
  { id: 1818, name: "Aghbal-BERKAN", ref: "Agh" },
  { id: 1852, name: "Aghbala-Beni Mellal", ref: "Agba" },
  { id: 1787, name: "Aghbalou Nserdan", ref: "Agb" },
  { id: 1539, name: "Aglou", ref: "Agl" },
  { id: 1964, name: "Agouim-Ouarzazate", ref: "Agoi" },
  { id: 1574, name: "Agouray - Meknes", ref: "Agou" },
  { id: 2225, name: "Agourram (Ait Amira)-agadir", ref: "agouram" },
  { id: 1729, name: "Aguelmous", ref: "Ags" },
  { id: 2155, name: "Aguidir-imintanout", ref: "guidr" },
  { id: 1605, name: "agzirt Beni-Mellal", ref: "agzir" },
  { id: 2099, name: "Ahdil-chichaoua", ref: "ahdil" },
  { id: 1761, name: "AHFIR", ref: "AHFR" },
  { id: 2339, name: "Ahl Marbae - Fquih Ben Salah", ref: "MRABAE" },
  { id: 2326, name: "Ahl souss", ref: "SOUSS" },
  { id: 2052, name: "Ahmar laglalcha-taroudant", ref: "lglcha" },
  { id: 1938, name: "ain aicha - taounate", ref: "aicha" },
  { id: 2016, name: "Ain Allah-fes", ref: "allh" },
  { id: 2000, name: "Ain Aouda-TEMARA", ref: "AND" },
  { id: 1995, name: "AIN ATTIQ-TEMARA", ref: "ATTQ" },
  { id: 2255, name: "Ain Baita-Ouazzane", ref: "Baita" },
  { id: 2115, name: "Ain Beida-chichaoua", ref: "Beida" },
  { id: 1807, name: "Ain Bita-sefrou", ref: "Bita" },
  { id: 1570, name: "Ain Bni Mathar", ref: "Mathar" },
  { id: 1461, name: "Ain Cheggag", ref: "Cheg" },
  { id: 1680, name: "Ain Chkef", ref: "Chkf" },
  { id: 2285, name: "Ain Choka-ksar sghir", ref: "Choka" },
  { id: 1655, name: "Ain Dfali-Ouazzane", ref: "Dfa" },
  { id: 1573, name: "Ain Dorij", ref: "Dorij" },
  { id: 1586, name: "Ain el Mediour", ref: "Mediour" },
  { id: 2127, name: "Aïn Erreggada", ref: "Erreg" },
  { id: 2251, name: "Ain Gfali -Ouazzane", ref: "Gfali" },
  { id: 235, name: "Ain Harouda", ref: "AHR" },
  { id: 2316, name: "Ain jamaa-errahma", ref: "jmarr" },
  { id: 1660, name: "Ain Jemaa-meknes", ref: "Jem" },
  { id: 1662, name: "Ain jiri-meknes", ref: "jiri" },
  { id: 364, name: "ain leuh", ref: "anl" },
  { id: 1939, name: "ain mediouna - taounate", ref: "mdn" },
  { id: 1749, name: "Ain Sbit-Khemisset", ref: "ansbt" },
  { id: 1583, name: "Ain Seddaq", ref: "Seddaq" },
  { id: 1619, name: "Ain Tekki", ref: "Tekki" },
  { id: 1689, name: "Ain Zarka", ref: "Zarka" },
  { id: 1882, name: "aine aghbal-meknes", ref: "agbl" },
  { id: 2214, name: "AIT AALA-tinghir", ref: "aala" },
  { id: 2222, name: "ait abdoun-boumalen dades", ref: "abdn" },
  { id: 1883, name: "ait ai3zam-meknes", ref: "ait" },
  { id: 1595, name: "Ait Aissa Oubrahim", ref: "Aissa" },
  { id: 2238, name: "Ait Ali Ougmas (Route Ifrane)-Azrou", ref: "ougms" },
  { id: 2236, name: "Ait Amer ou Ali (Route Sidi Addi)-Azrou", ref: "amerr" },
  { id: 1075, name: "AIT AMIRA-AGADIR", ref: "aita" },
  { id: 1859, name: "Ait Baha", ref: "Baha" },
  { id: 1814, name: "Ait Ben Haddou-Ouarzazate", ref: "Haddou" },
  { id: 2209, name: "Ait Boujan-tinghir", ref: "bjn" },
  { id: 2211, name: "Ait Daouen-tinghir", ref: "daoun" },
  { id: 2210, name: "Ait El Kadi-tinghir", ref: "KDI" },
  { id: 1863, name: "Aït Hadifa-Al Hoceima", ref: "Hafa" },
  { id: 1585, name: "Ait Iaaza", ref: "laza" },
  { id: 1596, name: "ait ihya omoussa-kelaa magouna", ref: "ihya" },
  { id: 1837, name: "Ait ishaq", ref: "ishq" },
  { id: 1780, name: "Ait Kamra-Hoceima", ref: "Kamra" },
  { id: 49, name: "Ait Melloul", ref: "AIL" },
  { id: 2208, name: "Ait Oujana-tinghir", ref: "ojn" },
  { id: 1634, name: "Ait ourir-MARRAKECH", ref: "AiTAO" },
  { id: 2268, name: "AIT TALEB-sefrou", ref: "tlbb" },
  { id: 2235, name: "Ait Yahya ou Alla (Route Sidi Addi)-Azrou", ref: "yhy" },
  { id: 1966, name: "Ait Zineb-Ouarzazate", ref: "Zineb" },
  { id: 1562, name: "Ajdir-HOUCIMA", ref: "Ajd" },
  { id: 1922, name: "Ajdir-taza", ref: "ajdr" },
  { id: 1923, name: "Akchour", ref: "AKCH" },
  { id: 1825, name: "Akhfennir", ref: "Feir" },
  { id: 1699, name: "Akka-tata", ref: "aka" },
  { id: 1821, name: "Aklim", ref: "Akl" },
  { id: 1878, name: "Aknoul-taza", ref: "aknl" },
  { id: 2077, name: "akrach-RABAT", ref: "akrach" },
  { id: 2283, name: "Al Ghadban-jadida", ref: "ghdbn" },
  { id: 2218, name: "Al Had (Hay Nahda)-kelaa mgouna", ref: "ALHAD" },
  { id: 55, name: "Al Hoceima", ref: "ALC" },
  { id: 2330, name: "Al Khalifa", ref: "khlf" },
  { id: 2216, name: "Al Maayach-kelaa mgouna", ref: "maaych" },
  { id: 2311, name: "Almaz-lissasfa", ref: "ALMAZ" },
  { id: 1546, name: "Alnif", ref: "Aln" },
  { id: 1813, name: "Amerzgane-Ouarzazate", ref: "Amgan" },
  { id: 2144, name: "Ameskroud-agadir", ref: "amskrd" },
  { id: 1765, name: "Amizmiz", ref: "Azmi" },
  { id: 2319, name: "Ansari-dar bouaza", ref: "ANSR" },
  { id: 963, name: "ANZA", ref: "ANZA" },
  { id: 2085, name: "ANZI-TIZNIT", ref: "ANZI" },
  { id: 1593, name: "Aoufous", ref: "Aouf" },
  { id: 1770, name: "Aoulouz", ref: "Aolz" },
  { id: 1549, name: "Aourir-Agadir", ref: "Aou" },
  { id: 2146, name: "aousserd-DAKHLA", ref: "AOUSS" },
  { id: 1803, name: "Arba Aounate-أربعاء العونات", ref: "Arba" },
  { id: 1909, name: "ARBAOUA", ref: "ARB" },
  { id: 1622, name: "Arjat-Mohammedia", ref: "Arjat" },
  { id: 2282, name: "Asfalou-ouarzazate", ref: "asflou" },
  { id: 2110, name: "Asif lmal-chichaoua", ref: "Asif" },
  { id: 1898, name: "ASILAH VILLE", ref: "asl" },
  { id: 2023, name: "Asni-marrakech", ref: "asni" },
  { id: 1827, name: "Assa-VILLE", ref: "VAssa" },
  { id: 2087, name: "Assahrij-KELAA DES SRAGHNA", ref: "Assahrij" },
  { id: 2113, name: "Asseratou-chichaoua", ref: "Asseratou" },
  { id: 1755, name: "Attaouia", ref: "Attui" },
  { id: 2266, name: "Ayoun Smar-sefrou", ref: "smr" },
  { id: 523, name: "AZEMMOUR", ref: "AZM" },
  { id: 1948, name: "AZILAL VILLE", ref: "AZZZ" },
  { id: 2227, name: "Azou (Ikhrban)", ref: "azro" },
  { id: 1847, name: "AZRO-AIT MELLOUL AGADIR", ref: "AZR" },
  { id: 327, name: "AZROU-VILLE", ref: "AZ" },
  { id: 2265, name: "Azzaba-sefrou", ref: "azzaba" },
  { id: 879, name: "Bab Berred", ref: "BABARD" },
  { id: 2259, name: "Bab Goghma Ouazzane-", ref: "Goghma" },
  { id: 1709, name: "Bab Taza", ref: "Batz" },
  { id: 2303, name: "bab tioula-sidi kacem", ref: "bab tioula" },
  { id: 1862, name: "Bani Hadifa-Al Hoceima", ref: "Hadifa" },
  { id: 1589, name: "Bdouza", ref: "Bdouz" },
  { id: 2342, name: "Bejaad", ref: "Bjaa" },
  { id: 1636, name: "Belaagid", ref: "Bela" },
  { id: 1342, name: "Belfaa", ref: "Belf" },
  { id: 1752, name: "BELKSIRI", ref: "BKRI" },
  { id: 1625, name: "Ben ahmed-Berrchid", ref: "Bnh" },
  { id: 601, name: "Ben Guerir", ref: "bng" },
  { id: 1977, name: "BEN TAYEB- DRIOUCH", ref: "TAY" },
  { id: 2279, name: "Ben Yaakoub-tata", ref: "Yaakoub" },
  { id: 2120, name: "beni elouida-azilal", ref: "elouidd" },
  { id: 907, name: "Beni Ensar", ref: "BNINSR" },
  { id: 73, name: "Beni Mellal", ref: "BML" },
  { id: 1935, name: "beni oulid - taounate", ref: "bnild" },
  { id: 1617, name: "Beni-Hassan-Chefchaouen", ref: "Hassa" },
  { id: 511, name: "Benslimane", ref: "BSLM" },
  { id: 2299, name: "Ber Taleb-sidi kacem", ref: "Ber Taleb" },
  { id: 1710, name: "Berkane", ref: "Bkn" },
  { id: 1558, name: "BERRECHID VILLE", ref: "BERR" },
  { id: 1916, name: "Bhalil-sefrou", ref: "bhl" },
  { id: 1068, name: "Biougra", ref: "BG" },
  { id: 2232, name: "Biougra:(Lkhrba)-agadir", ref: "Biougra" },
  { id: 2240, name: "Biougra(  Tin Hamou)-agadir", ref: "Hamou" },
  { id: 2237, name: "Biougra( Lghriss)-agadir", ref: "Lghriss" },
  { id: 2234, name: "Biougra(Ait Sayh)-agadir", ref: "Sayh" },
  { id: 2148, name: "bir gandouz dakhla", ref: "GNDZ" },
  { id: 1412, name: "Bir Jdid", ref: "Bir" },
  { id: 1870, name: "Bir Kouat", ref: "Kouat" },
  { id: 1971, name: "Bir Tam Tam", ref: "TAMTAM" },
  { id: 2246, name: "Birkwat-safi", ref: "birkwat" },
  { id: 1946, name: "Bni Ahmed - chefchaouen", ref: "bnih" },
  { id: 1611, name: "Bni Ayat - Beni-Mellal", ref: "Ayat" },
  { id: 1489, name: "Bni Bouayach", ref: "Boua" },
  { id: 1861, name: "Bni Boufrah-Al Hoceima", ref: "Bofra" },
  { id: 1820, name: "Bni Chiker", ref: "Chiker" },
  { id: 2072, name: "Bni Darkoul-chefchaouen", ref: "bnidrkl" },
  { id: 1794, name: "Bni Drar", ref: "drd" },
  { id: 2239, name: "Bni Mezoui-khouribgua", ref: "bnmz" },
  { id: 1620, name: "Bni Yakhlef", ref: "Yakhl" },
  { id: 1685, name: "bouanane-tetoun", ref: "bane" },
  { id: 2117, name: "bouanga-chichaoua", ref: "bnga" },
  { id: 1842, name: "BOUARFA", ref: "ARF" },
  { id: 1575, name: "Bouderbala-MEKNES", ref: "Boude" },
  { id: 1785, name: "Boudnib", ref: "Bodn" },
  { id: 773, name: "BOUFKRANE", ref: "BOFK" },
  { id: 1934, name: "bouhouda - taounate", ref: "bhd" },
  { id: 1828, name: "Bouizakarne-VILLE", ref: "Bozk" },
  { id: 91, name: "Boujdour", ref: "BJDR" },
  { id: 984, name: "Boujniba", ref: "bjni" },
  { id: 1779, name: "boukidan", ref: "bouk" },
  { id: 1988, name: "BOUKNADEL", ref: "BKNDL" },
  { id: 1690, name: "Boulanouare", ref: "Bol" },
  { id: 2131, name: "Boulemane-azrou", ref: "boulman" },
  { id: 1531, name: "Boumaln dads - tinghir", ref: "Dades" },
  { id: 1138, name: "Boumia", ref: "BouM" },
  { id: 1542, name: "Bounaamane-TIZNIT", ref: "Boa" },
  { id: 1739, name: "Bounouar-khouribga", ref: "Bor" },
  { id: 2193, name: "Bournazel-casablanca", ref: "brnzl" },
  { id: 421, name: "BOUSKOURA", ref: "BSK" },
  { id: 1884, name: "Boussmssad-meknes", ref: "bsmd" },
  { id: 472, name: "BOUZNIKA", ref: "BZ" },
  { id: 2335, name: "Bradia - Fquih Ben Salah", ref: "bradi" },
  { id: 2242, name: "Brakt Lamine-safi", ref: "brktln" },
  { id: 2241, name: "Brakt Radi-safi", ref: "brakt" },
  { id: 1902, name: "Brych-ASILAH", ref: "BRY" },
  { id: 271, name: "Cabo Negro", ref: "CNG" },
  { id: 2322, name: "Casabis-mediouna", ref: "CASABIS" },
  { id: 2178, name: "Casablanca – 2 Mars", ref: "2mars" },
  { id: 2188, name: "Casablanca – Ain Borja", ref: "brja" },
  { id: 2180, name: "Casablanca – Ain Chock", ref: "achok" },
  { id: 2173, name: "Casablanca – Ain Diab", ref: "adiab" },
  { id: 2184, name: "Casablanca – Ain Sebaa", ref: "sbaa" },
  { id: 2185, name: "Casablanca – Anassi", ref: "anss" },
  { id: 2190, name: "Casablanca – Anfa", ref: "anfa" },
  { id: 2170, name: "Casablanca – Beauséjour", ref: "bsejr" },
  { id: 2183, name: "Casablanca – Bernoussi", ref: "brns" },
  { id: 2172, name: "Casablanca – Bourgogne", ref: "rgon" },
  { id: 2181, name: "Casablanca – Californie", ref: "calif" },
  { id: 2174, name: "Casablanca – Centre Ville", ref: "ctrville" },
  { id: 2175, name: "Casablanca – Derb Omar", ref: "domar" },
  { id: 2176, name: "Casablanca – Derb Sultan", ref: "dseltan" },
  { id: 2182, name: "Casablanca – Hay Hassani", ref: "hssnI" },
  { id: 2187, name: "Casablanca – Hay Mohammadi", ref: "mhmd" },
  { id: 2166, name: "Casablanca – Lissasfa", ref: "lssf" },
  { id: 2179, name: "Casablanca – Maarif", ref: "maarif" },
  { id: 2167, name: "Casablanca – Moulay Rachid", ref: "mrachid" },
  { id: 2171, name: "Casablanca – Ouasis", ref: "ouasis" },
  { id: 2177, name: "Casablanca – Oulfa", ref: "olf" },
  { id: 2189, name: "Casablanca – Roches Noires", ref: "rchnr" },
  { id: 2169, name: "Casablanca – Sbata", ref: "sbata" },
  { id: 2165, name: "Casablanca – Sidi Maarouf", ref: "mrof" },
  { id: 2186, name: "Casablanca – Sidi Moumen", ref: "MMN" },
  { id: 2168, name: "Casablanca – Sidi Othmane", ref: "sotmn" },
  { id: 2323, name: "Casadia-daroua", ref: "casadia" },
  { id: 2156, name: "centre 44 - marrakech", ref: "cntr" },
  { id: 2340, name: "Chagar - Béni Mellal", ref: "CHAGAR" },
  { id: 1804, name: "Chaibate-el jadida", ref: "Chai" },
  { id: 2264, name: "Chbika-tantan", ref: "chbka" },
  { id: 583, name: "Chefchaouen", ref: "chf" },
  { id: 1145, name: "CHELLALAT", ref: "CHELLAL" },
  { id: 1648, name: "Chichaoua-VILLE", ref: "wch" },
  { id: 2318, name: "Chlihat-dar bouaza", ref: "CHLH" },
  { id: 2290, name: "Chnafa-sidi yahya", ref: "Chnafa" },
  { id: 1641, name: "Chouiter", ref: "Chotr" },
  { id: 1616, name: "CHRAFAT-Chefchaouen", ref: "CHRA" },
  { id: 103, name: "Dakhla", ref: "DAK" },
  { id: 1959, name: "Daliya_ksar sghir", ref: "dly" },
  { id: 415, name: "DAR BOUAZZA", ref: "DR" },
  { id: 1854, name: "Dar el Amri-Sidi Sliman", ref: "Amri" },
  { id: 2010, name: "DAR EL GADARI", ref: "DRGDR" },
  { id: 2226, name: "Dar El Jadida-souk larbaa", ref: "jddi" },
  { id: 1978, name: "DAR EL KABDANI-DRIOUCH", ref: "DRK" },
  { id: 1602, name: "Dar Ould Zidouh", ref: "Zidouh" },
  { id: 2306, name: "Dar16-errahma", ref: "DAR16" },
  { id: 493, name: "DAROUA", ref: "DRW" },
  { id: 2292, name: "dayat aicha -sidi yahya", ref: "daya" },
  { id: 1715, name: "dcheira", ref: "dch" },
  { id: 2121, name: "DEBDOU", ref: "DBDO" },
  { id: 1756, name: "Demnate", ref: "Dente" },
  { id: 1930, name: "Derdara-Chefchaouen", ref: "chefdrd" },
  { id: 2069, name: "Derdara-taroudant", ref: "drdr" },
  { id: 1905, name: "Dghaliyn-ASILAH", ref: "DGH" },
  { id: 1958, name: "Diki_ksar sghir", ref: "diki" },
  { id: 1661, name: "Dkhissa-meknes", ref: "Dkh" },
  { id: 2203, name: "Dlalha", ref: "Dllhaa" },
  { id: 1673, name: "Douar Boumaiz", ref: "Baiz" },
  { id: 2108, name: "Douar jdida-chichaoua", ref: "jda" },
  { id: 2219, name: "douar larab(ait amira)-agadir", ref: "douarlrb" },
  { id: 2047, name: "DOUAR LKASIT-NADOR", ref: "KST" },
  { id: 2046, name: "Douar Rja Fellah-nador", ref: "fellah" },
  { id: 2105, name: "Douar si omara-chichaoua", ref: "omara" },
  { id: 2021, name: "douar Zliligue-fes", ref: "douar" },
  { id: 2017, name: "Douiyat-fes", ref: "DOUY" },
  { id: 1328, name: "Drarga", ref: "Drar" },
  { id: 1974, name: "DRIOUCH VILLE", ref: "DRIO" },
  { id: 2142, name: "Echammaia-youssoufia", ref: "ACM" },
  { id: 1858, name: "El aouama-tanger", ref: "aoama" },
  { id: 2147, name: "el argoub-dakhla", ref: "ARGB" },
  { id: 1734, name: "El Borj-KHENIFRA", ref: "Borj" },
  { id: 2198, name: "El Borouj ville", ref: "brjj" },
  { id: 2054, name: "El boura-taroudant", ref: "boura" },
  { id: 1627, name: "El Gara-Berrchid", ref: "Gara" },
  { id: 1894, name: "EL HALHAL MEDIOUNA", ref: "LHAL" },
  { id: 2053, name: "El houmer-taroudant", ref: "houmer" },
  { id: 109, name: "El Jadida", ref: "EJD" },
  { id: 2271, name: "El Johra-Ouazzane", ref: "Johra" },
  { id: 1731, name: "El Kebab-KHENIFRA", ref: "Kebb" },
  { id: 2333, name: "El Kotma - Béni Mellal", ref: "kotma" },
  { id: 1601, name: "El Ksiba - Beni-Mellal", ref: "Ksiba" },
  { id: 1543, name: "El Maader El Kabir-TIZNIT", ref: "Maader" },
  { id: 1243, name: "El Mansouria", ref: "souria" },
  { id: 1969, name: "El Menzel - Sefrou", ref: "MZ" },
  { id: 1791, name: "El Ouatia", ref: "ATIA" },
  { id: 2308, name: "Elfajr-errahma", ref: "FAJR" },
  { id: 1363, name: "ElHajeb VILLE", ref: "ajeb" },
  { id: 1257, name: "Erfoud VILLE", ref: "ARRE" },
  { id: 607, name: "ERRACHIDIA", ref: "ERR" },
  { id: 403, name: "ERRAHMA VILLE", ref: "ER" },
  { id: 1728, name: "Essaouira الصويرة", ref: "ESRW" },
  { id: 1792, name: "Essemara-السمارة", ref: "mara" },
  { id: 1967, name: "Ezzhiliga", ref: "ezz" },
  { id: 1701, name: "Fam El Hisn-tata", ref: "Hisn" },
  { id: 1819, name: "ferkhana-nador", ref: "ferkh" },
  { id: 127, name: "Fes", ref: "FES" },
  { id: 1841, name: "FIGUIG", ref: "FIG" },
  { id: 133, name: "Fnideq", ref: "FNI" },
  { id: 2107, name: "Forina-chichaoua", ref: "forina" },
  { id: 1951, name: "foum jamaa-Azilal", ref: "FMJMA" },
  { id: 1741, name: "Foum Oudi-زاوية", ref: "Oudi" },
  { id: 1700, name: "Foum Zguid", ref: "Zgd" },
  { id: 1881, name: "Fouwarat-meknes", ref: "Frt" },
  { id: 2324, name: "fquih ben saleh", ref: "rfg" },
  { id: 2088, name: "Fraita-kelaa des sraghna", ref: "Fraita" },
  { id: 1942, name: "galaz - taounate", ref: "galaz" },
  { id: 1580, name: "Gfifat", ref: "Gfif" },
  { id: 1920, name: "Ghafsai", ref: "ghfs" },
  { id: 2162, name: "Ghmat-marrakech", ref: "ghmat" },
  { id: 1632, name: "Gouassem-VILLE", ref: "Gouass" },
  { id: 1286, name: "Goulmima-errachidia", ref: "Goul" },
  { id: 1788, name: "Gourrama", ref: "grma" },
  { id: 2304, name: "grinat-sidi kacem", ref: "grinat" },
  { id: 1824, name: "Guelmim-ville", ref: "Glj" },
  { id: 1873, name: "Guercif", ref: "grcf" },
  { id: 2149, name: "guerguerat-DAKHLA", ref: "GRG" },
  { id: 1723, name: "Guigou-Azrou", ref: "Ggu" },
  { id: 1683, name: "Guisser-settat", ref: "Gui" },
  { id: 1839, name: "Had bouhssoussen", ref: "had" },
  { id: 2243, name: "Had Dra-safi", ref: "hddra" },
  { id: 1868, name: "Had Draa", ref: "Draa" },
  { id: 1556, name: "Had Hrara-SAFI", ref: "Hrara" },
  { id: 1572, name: "Had Kourt", ref: "Kourt" },
  { id: 1900, name: "Had lgharbiya-ASILAH", ref: "GHRB" },
  { id: 1911, name: "Had Oulad Aissa", ref: "WAISSA" },
  { id: 724, name: "had soualem", ref: "HDS" },
  { id: 1569, name: "HAD WLAD FRAJ", ref: "FRAJ" },
  { id: 2135, name: "Hadada – Youssoufia", ref: "Hdd" },
  { id: 2005, name: "Hadd Ouled Jelloul-TAZI", ref: "TZI" },
  { id: 1943, name: "hajria - taounate", ref: "hajria" },
  { id: 2080, name: "Harat el morabitine-tinghir", ref: "hrtmrbt" },
  { id: 1996, name: "HARHOURA", ref: "HRH" },
  { id: 1737, name: "Hattane-Khouribga", ref: "Hate" },
  { id: 2295, name: "helalia-sidi yahya", ref: "helalia" },
  { id: 1321, name: "Houara", ref: "Hou" },
  { id: 2275, name: "Idlsan-ouarzazate", ref: "idlsan" },
  { id: 2043, name: "IEASSEN-nador", ref: "IEASSEN" },
  { id: 333, name: "IFRAN", ref: "IF" },
  { id: 2195, name: "ighloud-echemmaia", ref: "ighld" },
  { id: 2039, name: "IGHMARIYIN-nador", ref: "ghmr" },
  { id: 1606, name: "ighram laalam-beni mellal", ref: "ighram" },
  { id: 2060, name: "ighram-taroudant", ref: "ighrm" },
  { id: 1965, name: "ighrem Nougdal-Ouarzazate", ref: "ighem" },
  { id: 2031, name: "IHDADEN-nador", ref: "hddn" },
  { id: 2278, name: "Iligh-tata", ref: " Iligh  " },
  { id: 2034, name: "IMACHROUBEN-nador", ref: "mchrb" },
  { id: 2035, name: "IMEHARFEN-nador", ref: "mhrfn" },
  { id: 2277, name: "Imghran-ouarzazate", ref: "IMGHRN" },
  { id: 1598, name: "Imgon-Tinghir", ref: "Img" },
  { id: 2013, name: "Imi Ouaddar-agadir", ref: "ouddr" },
  { id: 2092, name: "iminifri - kelaa des sraghna", ref: "iminifri" },
  { id: 2151, name: "Iminitanoute", ref: "Imnt" },
  { id: 2274, name: "Imitk-tata", ref: "Imitk  " },
  { id: 339, name: "IMOUZAR KANDRE", ref: "IMZ" },
  { id: 2132, name: "imouzzar marmoucha-azrou", ref: "immzzr" },
  { id: 2123, name: "imsouane-agadir", ref: "imso" },
  { id: 1482, name: "imzouren", ref: "Imzm" },
  { id: 2143, name: "Inchaden-agadir", ref: "INCH" },
  { id: 151, name: "Inzegane", ref: "INZ" },
  { id: 2307, name: "Iraki-errahma", ref: "Iraki" },
  { id: 2033, name: "ISAKKAJEN-nador", ref: "skkjn" },
  { id: 1702, name: "Issafen-tata", ref: "Issa" },
  { id: 1692, name: "Issaguen", ref: "Isgue" },
  { id: 2223, name: "Issen (Drarga – Route Houara)-agadir", ref: "issen" },
  { id: 1786, name: "ITZER", ref: "Itzer" },
  { id: 2029, name: "JAADAR-nador", ref: "jaad" },
  { id: 1618, name: "jamaat fdala", ref: "jamaat" },
  { id: 1784, name: "Jamaat foko-Berrchid", ref: "foko" },
  { id: 2096, name: "Jamaat larracha - Kelaâ des Sraghna", ref: "jmaat" },
  { id: 2315, name: "Jamaat melilla-bensliman", ref: "JAMAT" },
  { id: 1778, name: "Jamaat Riah-Berrchid", ref: "Riah" },
  { id: 427, name: "Jamaat shaim", ref: "JMS" },
  { id: 2075, name: "Jaqma-berrchid", ref: "jaqma" },
  { id: 1925, name: "JEBHA", ref: "Jha" },
  { id: 2331, name: "Jemaa ahl merbaa", ref: "MRB" },
  { id: 2231, name: "Jemâa El Houdrane-khemisset", ref: "jmaa" },
  { id: 1384, name: "Jerada", ref: "Jer" },
  { id: 1903, name: "Jilaliya-ASILAH", ref: "JL" },
  { id: 2253, name: "Jmaâat Bni Kola-Ouazzane", ref: "Bni Kola" },
  { id: 2263, name: "Jmaât Ben Khlil-tantan", ref: "jmat" },
  { id: 2267, name: "Jmaât Beni Oual-Ouazzane", ref: "Beni Oual" },
  { id: 2262, name: "Jmaât Brikcha-Ouazzane", ref: "Brikcha  " },
  { id: 2269, name: "Jmaât Mouqrita-ouazzan", ref: "Mouqrita" },
  { id: 2317, name: "Jmaiaa-bouskoura", ref: "JAMAIA" },
  { id: 1571, name: "Jorf El Melha-OUZZANE", ref: "Jorf" },
  { id: 1564, name: "Jorf Sefar", ref: "sefar" },
  { id: 2160, name: "Jorf-erfoud", ref: "jrf" },
  { id: 2093, name: "Jwala-kelaa des sraghna", ref: "jwala" },
  { id: 1687, name: "Kabila", ref: "Kabi" },
  { id: 2048, name: "KACHADIA-NADOR", ref: "KCHD" },
  { id: 2294, name: "Kachla-sidi yahya", ref: "kachla" },
  { id: 1732, name: "Kaf Nsour-KHENIRA", ref: "Nsours" },
  { id: 1989, name: "kamouni", ref: "KMN" },
  { id: 1933, name: "kantra askar - taounate", ref: "kntr" },
  { id: 1555, name: "Kariat Arkman‎-Nador", ref: "Arkman" },
  { id: 1468, name: "Kariat Ba Mohamed", ref: "Kariat" },
  { id: 157, name: "Kasba Tadla", ref: "KAS" },
  { id: 2081, name: "Kasba tadla-oulad yaich-benimellal", ref: "ksb" },
  { id: 2082, name: "Kasba tadla-oulad youssef-beni mellal", ref: "ysssf" },
  { id: 1578, name: "Kasbah El Taher", ref: "Taher" },
  { id: 1980, name: "Kasita-DRIOUCH", ref: "KASITA" },
  { id: 1754, name: "Kelâa des Sraghna", ref: "Srgn" },
  { id: 1391, name: "Kelâat M Gouna-قلعة امڭونة", ref: "Gouna" },
  { id: 949, name: "KELIAA", ref: "KLIAA" },
  { id: 1089, name: "KENITRA VILLE", ref: "KNVI" },
  { id: 2025, name: "Ketama-houcima", ref: "KTM" },
  { id: 1929, name: "Khamis M Diq-chefchaouen", ref: "khmdq" },
  { id: 2065, name: "Khdadra-ksar el kbir", ref: "khdr" },
  { id: 2224, name: "Khemis Dades -boumalen dades", ref: "dadess" },
  { id: 2220, name: "Khemis Dades -kelaa mgouna", ref: "khmsd" },
  { id: 2250, name: "Khemis Meskala-Essaouira", ref: "khmsskl" },
  { id: 1669, name: "Khemis Sahel", ref: "Sah" },
  { id: 1750, name: "khemis zemamra", ref: "zmmr" },
  { id: 1271, name: "Khemisset ville", ref: "Khem" },
  { id: 1671, name: "Khenichet-SIDI KACEM", ref: "Khei" },
  { id: 1711, name: "KHENIFRA VILLE", ref: "khnf" },
  { id: 1932, name: "Khlalfa-Taounate", ref: "khllf" },
  { id: 2139, name: "Khnoufa – Youssoufia", ref: "KHNOUFA" },
  { id: 169, name: "Khouribga", ref: "KHO" },
  { id: 2140, name: "Khwalqa – Youssoufia", ref: "Khwalqa" },
  { id: 2070, name: "khzana-chefchaouen", ref: "KHZN" },
  { id: 1805, name: "Kouassem-el jadida", ref: "Koua" },
  { id: 2254, name: "Krimat-essaouira", ref: "krimat" },
  { id: 1908, name: "Ksar El Kebir", ref: "KS" },
  { id: 2287, name: "Ksar Lmajaz- ksar Sghir", ref: "Lmajaz" },
  { id: 1919, name: "ksar sghir", ref: "ksrss" },
  { id: 1889, name: "Kwidar-meknes", ref: "kdr" },
  { id: 2328, name: "Laajana", ref: "laajan" },
  { id: 1990, name: "LAARJATE", ref: "LRJT" },
  { id: 886, name: "LAAROUI", ref: "AROUI" },
  { id: 2125, name: "Laâtamna", ref: "Lata" },
  { id: 2094, name: "Laâtamna-kelaa des sraghna", ref: "laatmn" },
  { id: 1832, name: "LAAYOUNE-PLAYA", ref: "PLYA" },
  { id: 1831, name: "LAAYOUNE-PORT", ref: "PRT" },
  { id: 1830, name: "Laayoune-ville", ref: "Layn" },
  { id: 2309, name: "Labissa-bouskoura", ref: "LBSS" },
  { id: 2305, name: "Labza-sidi kacem", ref: "labza" },
  { id: 2329, name: "Lahlalma", ref: "lhlm" },
  { id: 2192, name: "Lahraouyine-casablanca", ref: "hrouin" },
  { id: 1906, name: "Lakhssas", ref: "Lakhsa" },
  { id: 2111, name: "Lalla aziza-chichaoua", ref: "lallaazz" },
  { id: 2291, name: "Lalla btoul / Lwzar (sidi yahya)", ref: "Bṭoul" },
  { id: 1588, name: "Lalla Fatna", ref: "Fatna" },
  { id: 1753, name: "Lalla Mimouna", ref: "MIMNA" },
  { id: 1766, name: "Lalla Takerkoust", ref: "Take" },
  { id: 2129, name: "Lamriss", ref: "Lamriss" },
  { id: 1599, name: "Laouamra", ref: "Laoua" },
  { id: 187, name: "Larache", ref: "LAR" },
  { id: 1398, name: "Layoun cherkia-العيون الشرقية", ref: "Aion" },
  { id: 1733, name: "Lehri-KHENIFRA", ref: "Lehri" },
  { id: 2296, name: "Lghyabat-sidi sliman", ref: "Lghyabat" },
  { id: 801, name: "LHAJ KADOUR VILLE", ref: "HJK" },
  { id: 1567, name: "Lhawzia-JADIDA", ref: "Lhawz" },
  { id: 2091, name: "Lhmadna-kelaa des sraghna", ref: "lhmadna" },
  { id: 2310, name: "Lilasparck-bouskoura", ref: "LILAS" },
  { id: 1893, name: "lkhyayta-had soualem", ref: "khyay" },
  { id: 2154, name: "Lmakina-imintanout", ref: "Mkn" },
  { id: 794, name: "LMHAYA", ref: "lMH" },
  { id: 2159, name: "lmnabha-marrakech", ref: "mnbh" },
  { id: 1955, name: "Lmnar Park-ksar sghir", ref: "lmnr" },
  { id: 2297, name: "Lmssada-sidi sliman", ref: "Lmssada" },
  { id: 2032, name: "LOMMAL-nador", ref: "lmml" },
  { id: 2137, name: "Louihat – Youssoufia", ref: "louihat" },
  { id: 1561, name: "Louizia", ref: "Loui" },
  { id: 1890, name: "Lozin-meknes", ref: "lzn" },
  { id: 193, name: "M Diq", ref: "MDQ" },
  { id: 1991, name: "MAAMORA", ref: "MAAMRA" },
  { id: 1544, name: "Maaziz", ref: "Mzi" },
  { id: 2163, name: "Madagh-berkane", ref: "mdgh" },
  { id: 1904, name: "Marghouba-ASILAH", ref: "MGH" },
  { id: 1686, name: "marina smir", ref: "smir" },
  { id: 199, name: "Marrakech", ref: "MRK" },
  { id: 205, name: "Martil", ref: "MAM" },
  { id: 1768, name: "Marzouga", ref: "Marz" },
  { id: 1656, name: "Masmouda - Ouazzane", ref: "Mas" },
  { id: 2001, name: "Massa", ref: "Msasa" },
  { id: 2014, name: "massa chtouka-agadir", ref: "mssa" },
  { id: 1565, name: "Mazagan", ref: "Maza" },
  { id: 2126, name: "MDAR", ref: "MDA" },
  { id: 571, name: "Mediouna", ref: "MEDA" },
  { id: 1082, name: "MEHDIA", ref: "meh" },
  { id: 1096, name: "MEHDIA VILLE", ref: "MHDV" },
  { id: 2152, name: "Mejjat-imintanout", ref: "mjjt" },
  { id: 1846, name: "Mejjat-meknes", ref: "Mejte" },
  { id: 211, name: "Meknes", ref: "MEK" },
  { id: 2150, name: "MELJAW-ASILAH", ref: "MLJW" },
  { id: 1999, name: "MERS EL KHIR", ref: "MRSKH" },
  { id: 1945, name: "mezraoua - taounate", ref: "mezraoua" },
  { id: 1131, name: "MHamid El Ghizlane", ref: "MHa" },
  { id: 1975, name: "Midar-Driouch", ref: "MIDA" },
  { id: 535, name: "MIDELT", ref: "MDL" },
  { id: 1623, name: "Mimosa-mohammedia", ref: "Mimos" },
  { id: 1782, name: "mirleft", ref: "mirl" },
  { id: 1264, name: "Missour", ref: "Miss" },
  { id: 2252, name: "Mji (entre Hanchan et Tafdacht)-essaouira", ref: "mjji" },
  { id: 1895, name: "MKANSA-MEDIOUNA", ref: "KAN" },
  { id: 2007, name: "Mograne-TAZI", ref: "MGRN" },
  { id: 345, name: "Mohammedia", ref: "MH" },
  { id: 787, name: "MOLY DRISSE ZARHOUNE", ref: "MLDRI" },
  { id: 2247, name: "MOUL EL BERGUI-safi", ref: "mlbrg" },
  { id: 529, name: "MOULAY ABDELLAH", ref: "MLY" },
  { id: 1840, name: "Moulay bouazza khenifra", ref: "ML" },
  { id: 2202, name: "Moulay Bouselham", ref: "Bslhmm" },
  { id: 1440, name: "Moulay Yaâcoub", ref: "Yaa" },
  { id: 1720, name: "Mrirt Ville", ref: "Mrirt" },
  { id: 1712, name: "Mrirte", ref: "mrie" },
  { id: 1566, name: "Msawar Raso", ref: "Raso" },
  { id: 1597, name: "Msemrir-Tinghir", ref: "Msemr" },
  { id: 2256, name: "Msseyed-tantan", ref: "msseyed" },
  { id: 2314, name: "Mzabiyin-bouskoura", ref: "MZABI" },
  { id: 2153, name: "mzouda-imintanout", ref: "mzoda" },
  { id: 1736, name: "Mzoudia", ref: "Mzdi" },
  { id: 217, name: "Nador", ref: "NAD" },
  { id: 2109, name: "Nfifa-chichaoua", ref: "Nfifa" },
  { id: 1760, name: "NKob Zagora", ref: "nkob" },
  { id: 433, name: "Nouaceur", ref: "NSR" },
  { id: 2058, name: "nouail-taroudant", ref: "nouail" },
  { id: 2114, name: "Nowasser-chichaoua", ref: "Nsser" },
  { id: 1956, name: "Nwinwich_ksar sghir", ref: "nw" },
  { id: 1886, name: "Nzala-meknes", ref: "nzl" },
  { id: 2061, name: "nzalat laadam-benguerir", ref: "nzlt" },
  { id: 2097, name: "Nzalat Laadam-benguerir", ref: "nzalat" },
  { id: 1639, name: "Ouahat Sidi Brahim", ref: "Ouaha" },
  { id: 2040, name: "OUAHDANA-nador", ref: "ohdn" },
  { id: 1300, name: "OUALMES VILLE", ref: "OULM" },
  { id: 1950, name: "ouaouizeght-AZILAL", ref: "OUAOUI" },
  { id: 1838, name: "Ouaoumana", ref: "ouaoumana" },
  { id: 223, name: "Ouarzazat", ref: "OUZ" },
  { id: 1040, name: "Ouazzane", ref: "OZN" },
  { id: 1560, name: "OUDAYA-Marrakech", ref: "OUDAY" },
  { id: 1876, name: "Oued Amlil", ref: "od" },
  { id: 1688, name: "Oued Laou", ref: "Laou" },
  { id: 2320, name: "Oued merzeg-dar bouaza", ref: "MRZG" },
  { id: 2300, name: "Oued Rman- sidi kacem", ref: "Oued Rman" },
  { id: 2341, name: "Oued zem", ref: "Ouedzm" },
  { id: 229, name: "Oujda", ref: "OUJ" },
  { id: 1777, name: "Oulad Abbou-Berrchid", ref: "Abbo" },
  { id: 2042, name: "OULAD AISSA-nador", ref: "aissan" },
  { id: 1603, name: "Oulad Ayad", ref: "Ayad" },
  { id: 2337, name: "Oulad Ayoub - Fquih Ben Salah", ref: "ayb" },
  { id: 1584, name: "Oulad Berhil", ref: "Berhil" },
  { id: 2293, name: "Oulad bourahma-sidi yahya", ref: "rahma" },
  { id: 2051, name: "Oulad brahim-taroudant", ref: "brhmm" },
  { id: 1581, name: "Oulad Dahou", ref: "Dahou" },
  { id: 1745, name: "Oulad Hamdane-El Jadida", ref: "Hadn" },
  { id: 2020, name: "Oulad Hammou-fes", ref: "hmm" },
  { id: 2124, name: "Oulad hassoun-marrakech", ref: "HSSN" },
  { id: 1541, name: "oulad jerrar-Tiznit", ref: "jerrar" },
  { id: 2090, name: "Oulad Khallouf -Kelaâ des Sraghna", ref: "KHLLLF" },
  { id: 1743, name: "Oulad M barek-Beni Mellal", ref: "brek" },
  { id: 2059, name: "oulad mhela-taroudant", ref: "oldmhla" },
  { id: 2338, name: "Oulad Rbiâa - Fquih Ben Salah", ref: "RBIAA" },
  { id: 1612, name: "Oulad Said-Beni Mellal", ref: "Said" },
  { id: 1682, name: "Oulad Said-settat", ref: "Sad" },
  { id: 1892, name: "Oulad Salah-bouskoura", ref: "BSSK" },
  { id: 2067, name: "Oulad Sbaita-assilah", ref: "sbaita" },
  { id: 2019, name: "Oulad Tayeb-fes", ref: "tyb" },
  { id: 956, name: "Oulad Teima", ref: "OULDTAIMA" },
  { id: 2056, name: "oulad terna-taroudant", ref: "oldtrn" },
  { id: 2100, name: "Oulad Yaïch-chichaoua", ref: "oldych" },
  { id: 1609, name: "Oulad Zmam - Beni-Mellal", ref: "Zmam" },
  { id: 2332, name: "Ouled abdellah", ref: "ABDL" },
  { id: 2321, name: "Ouled Azzouz-dar bouaza", ref: "AZZOUZ" },
  { id: 1637, name: "OULED BEN RAHMOUN", ref: "RAHM" },
  { id: 1672, name: "Ouled Boutabet", ref: "oldb" },
  { id: 2158, name: "Ouled dlim - marrakech", ref: "dlim" },
  { id: 2327, name: "Ouled driss", ref: "driss" },
  { id: 1744, name: "Ouled Moussa-Beni Mellal", ref: "Msa" },
  { id: 2325, name: "Ouled rguiaa", ref: "rguiaa" },
  { id: 2068, name: "Ouled riahi-assilah", ref: "riahi" },
  { id: 2041, name: "OULED SALEM-NADOR", ref: "SLMD" },
  { id: 1986, name: "OUM AZZA", ref: "OMAZZ" },
  { id: 1869, name: "ounagha", ref: "ouagha" },
  { id: 2245, name: "Ounagha-safi", ref: "ounaga" },
  { id: 1631, name: "Ourika-VILLE", ref: "OuriK" },
  { id: 1944, name: "ourtzagh - taounate", ref: "ourtzagh" },
  { id: 1628, name: "Outat El Haj", ref: "Haj" },
  { id: 2301, name: "outitba-sidi kacem", ref: "outitba" },
  { id: 1867, name: "ouzioua", ref: "ozioa" },
  { id: 1621, name: "Plage David-Bouznika", ref: "David" },
  { id: 2036, name: "POBLAW-nador", ref: "pblw" },
  { id: 2045, name: "Quartier Al Boustane-nador", ref: "bstn" },
  { id: 2157, name: "Quetara- marrakech", ref: "qtr" },
  { id: 1984, name: "Rabat", ref: "RABT" },
  { id: 2136, name: "Ras El Ain – Youssoufia", ref: "rsain" },
  { id: 2233, name: "Ras El Ain-settat", ref: "ainras" },
  { id: 2118, name: "Ras El Ma-berkan", ref: "BRKMA" },
  { id: 1454, name: "Ras El Ma-FES", ref: "Ras" },
  { id: 2261, name: "Ras Oum Lile-tantan", ref: "rasoum" },
  { id: 1972, name: "Ras Tabouda", ref: "TBD" },
  { id: 1968, name: "Ribate El Kheir", ref: "rbtkh" },
  { id: 619, name: "RICHE-02", ref: "RICH-" },
  { id: 1250, name: "RISSANI VILLE", ref: "RIS" },
  { id: 1314, name: "ROMMANI VILLE", ref: "ROM" },
  { id: 1860, name: "Rouadi-Al Hoceima", ref: "Roua" },
  { id: 2030, name: "ROUISSI-nador", ref: "rss" },
  { id: 1762, name: "SAAIDIA", ref: "SADII" },
  { id: 61, name: "Safi", ref: "SFI" },
  { id: 2063, name: "Salama-ksar el kbir", ref: "salama" },
  { id: 1982, name: "SALE", ref: "SALE" },
  { id: 1983, name: "Sale El Jadida", ref: "SLEJ" },
  { id: 2101, name: "Samba-chichaoua", ref: "samba" },
  { id: 2270, name: "Sanhaja-sefrou", ref: "snhj" },
  { id: 780, name: "Sbaa Ayoune", ref: "SBY" },
  { id: 2134, name: "Sbiaat – Youssoufia", ref: "Sbiaat" },
  { id: 1545, name: "Sebt El Guerdane", ref: "grd" },
  { id: 439, name: "SEBT GZOULA", ref: "SBT" },
  { id: 2027, name: "Sebt Jahjouhe-meknes", ref: "jhjh" },
  { id: 2071, name: "sebt malha-chefchaouen", ref: "sbtmlh" },
  { id: 2286, name: "Sebt Oulad Bouaziz-jadida", ref: "bouaziz" },
  { id: 2284, name: "Sebt Oulad Douib-jadida", ref: "douib" },
  { id: 1747, name: "Sebt Saiss", ref: "Saiss" },
  { id: 1914, name: "sefrou", ref: "sfr" },
  { id: 900, name: "Segangan-nador", ref: "ZGN" },
  { id: 2076, name: "sehoul-sale", ref: "sehoul" },
  { id: 893, name: "Selouane", ref: "SLWNE" },
  { id: 1651, name: "Settate", ref: "Sts" },
  { id: 1973, name: "Sfassif-khemisset", ref: "stass" },
  { id: 1697, name: "Sid L Mokhtar", ref: "Mka" },
  { id: 1626, name: "Sid Zouine", ref: "Zouine" },
  { id: 370, name: "sidi aadi - azrou", ref: "sda" },
  { id: 1746, name: "Sidi Abbad", ref: "Abbad" },
  { id: 2298, name: "sidi abdelaziz-sidi slimane", ref: "abdelaziz" },
  { id: 2089, name: "Sidi Aissa Ben Slimane-kelaa des sraghna", ref: "slmnn" },
  { id: 1607, name: "Sidi Aissa-Beni-Mellal", ref: "SAissa" },
  { id: 2006, name: "Sidi Al Kamel-TAZI", ref: "KML" },
  { id: 2024, name: "Sidi ali ben hamdoch-jadida", ref: "hmdch" },
  { id: 1992, name: "Sidi Allal El Bahraoui", ref: "BHR" },
  { id: 2002, name: "sidi Allal Tazi", ref: "sdal" },
  { id: 1772, name: "Sidi Ayache", ref: "aayc" },
  { id: 935, name: "Sidi Bennour", ref: "BANOUR" },
  { id: 2312, name: "Sidi bettach-bensliman", ref: "Bettach" },
  { id: 1640, name: "Sidi Bou Othmane-VILLE", ref: "SiDBO" },
  { id: 2164, name: "sidi bouhriya-berkane", ref: "bhry" },
  { id: 2248, name: "Sidi Bousbar-Ouazzane", ref: "Bousbar" },
  { id: 1563, name: "Sidi Bouzid-EL JADIDA", ref: "Bouzid" },
  { id: 1767, name: "Sidi Bouzid-SAFI", ref: "Bosf" },
  { id: 1735, name: "Sidi Chiker", ref: "Chik" },
  { id: 2138, name: "Sidi Chiker – Youssoufia", ref: "SCHIKER" },
  { id: 2141, name: "sidi el aidi-berrchid", ref: "sdaaid" },
  { id: 1941, name: "sidi el makhfi - taounate", ref: "mkhf" },
  { id: 1638, name: "Sidi Ghiat", ref: "Ghia" },
  { id: 1783, name: "Sidi Hajjaj-Berrchid", ref: "Haja" },
  { id: 1419, name: "sidi hajjaj-casa", ref: "sbit" },
  { id: 1447, name: "Sidi Harazem", ref: "Hara" },
  { id: 1826, name: "SIDI IFNI-VILLE", ref: "SFNI" },
  { id: 2336, name: "Sidi Jaber - Fquih Ben Salah", ref: "JAB" },
  { id: 457, name: "SIDI KACEM", ref: "SDK" },
  { id: 1798, name: "SIDI KAML", ref: "KAML" },
  { id: 1124, name: "Sidi Kaouki-ESSOUIRA", ref: "Kaouki" },
  { id: 1899, name: "Sidi lyamani-ASILAH", ref: "YMN" },
  { id: 1897, name: "Sidi Moussa Ben Ali", ref: "ussa" },
  { id: 1896, name: "Sidi Moussa El Majdoub", ref: "Majd" },
  { id: 2050, name: "Sidi moussa lhamri-TAROUDANT", ref: "SDMOUSSA" },
  { id: 1866, name: "sidi ouaaziz", ref: "aaziz" },
  { id: 731, name: "Sidi Rahhal", ref: "SDR" },
  { id: 2249, name: "Sidi Redouane-Ouazzane", ref: "Redouane" },
  { id: 463, name: "SIDI SLIMAN", ref: "SDS" },
  { id: 1657, name: "Sidi Taibi", ref: "Tai" },
  { id: 2011, name: "sidi yahia elgharb", ref: "SDYH" },
  { id: 1998, name: "Sidi Yahya Zaer", ref: "YHYZ" },
  { id: 942, name: "Sidi-Bibi", ref: "SIDIBIBI" },
  { id: 2018, name: "Skhinate-fes", ref: "skht" },
  { id: 1997, name: "SKHIRAT", ref: "SKH" },
  { id: 1019, name: "Skhour Rehamna", ref: "SKHOR" },
  { id: 1812, name: "Skoura-Ouarzazate", ref: "Skoura" },
  { id: 1811, name: "Smimou - Essaouira", ref: "Smimou" },
  { id: 2064, name: "snadla-ksar el kbir", ref: "sndl" },
  { id: 1644, name: "Souihla-VILLE", ref: "Soui" },
  { id: 445, name: "Souiria آسفي", ref: "SRI" },
  { id: 1928, name: "Souk al had Ouazzane", ref: "skhd" },
  { id: 2230, name: "Souk El Had Oulad Jelloul-souk larbaa", ref: "hadold" },
  { id: 1751, name: "SOUK LARBAA", ref: "SKR" },
  { id: 2272, name: "Souk Larbaa Sebah (Skhirat)", ref: "SEBAH" },
  { id: 1885, name: "Souk lgor-meknes", ref: "sklgr" },
  { id: 2003, name: "SOUK LHAD ALLAL TAZI", ref: "SKLH" },
  { id: 2302, name: "Souk Lhad-sidi kacem", ref: "souk lhad" },
  { id: 1356, name: "Souk Sebt Oulad Nemma", ref: "Nemma" },
  { id: 2228, name: "Souk Tlat Gharb-souk larbaa", ref: "tlatt" },
  { id: 1927, name: "Souk Tlata Tanquoub Ouazzane", ref: "skou" },
  { id: 2008, name: "Souk Tlet El Gharb", ref: "SKTL" },
  { id: 1924, name: "STEHAT-OUED LAOU", ref: "STHT" },
  { id: 2004, name: "SWASIYIN ALAL TAZI", ref: "SWSY" },
  { id: 2191, name: "Tacharouk-casablanca", ref: "tchrk" },
  { id: 1877, name: "Taddart-taza", ref: "tdrt" },
  { id: 2194, name: "Tafetachte-essaouira", ref: "tftcht" },
  { id: 1793, name: "Tafoughalt", ref: "Tafg" },
  { id: 1540, name: "Tafraoute", ref: "Tafra" },
  { id: 1979, name: "Tafrsit-DRIOUCH", ref: "TAFRIST" },
  { id: 2206, name: "TAGANT-guelmim", ref: "TGNT" },
  { id: 1547, name: "Taghazout", ref: "Tagh" },
  { id: 2204, name: "Taghjijt-guelmim", ref: "TGHJT" },
  { id: 2078, name: "Taghzot- tinghir ville", ref: "Taghzot" },
  { id: 1703, name: "Tagmout-tata", ref: "Tagm" },
  { id: 1668, name: "Tagounite‬-zagora", ref: "Tagn" },
  { id: 1901, name: "Tahadart - ASILAH", ref: "THDRT" },
  { id: 1633, name: "Tahanaout-VILLE", ref: "Tahan" },
  { id: 1931, name: "tahar souk - TAOUNATE", ref: "thsk" },
  { id: 1875, name: "tahla", ref: "th" },
  { id: 1769, name: "Taliouine", ref: "Tali" },
  { id: 1871, name: "Talmest", ref: "Talmst" },
  { id: 2244, name: "talmest-safi", ref: "talmest" },
  { id: 2196, name: "Talsinnt", ref: "tlsnt" },
  { id: 2012, name: "Tamait Izder-agadir", ref: "izdr" },
  { id: 2057, name: "tamaloukt-taroudant", ref: "tmlkt" },
  { id: 1810, name: "Tamanar-Essaouira", ref: "Tamanar" },
  { id: 2273, name: "Tamanart-tata", ref: "Tamanart" },
  { id: 1559, name: "Tamansourt-Marrakech", ref: "Tama" },
  { id: 409, name: "TAMARIS", ref: "TM" },
  { id: 1667, name: "Tamegroute-zagora", ref: "Tag" },
  { id: 1757, name: "Tamellalt", ref: "Taml" },
  { id: 1647, name: "Tamesluht- VILLE", ref: "Tames" },
  { id: 1994, name: "TAMESNA-TEMARA", ref: "TMSN" },
  { id: 1579, name: "Tamraght", ref: "Tamrag" },
  { id: 1548, name: "Tamraght-Agadir", ref: "Tamr" },
  { id: 2122, name: "Tamri-agadir", ref: "Tamri" },
  { id: 1759, name: "Tamzmout zagora", ref: "Tamzt" },
  { id: 1949, name: "TANANTE-AZILAL", ref: "TANAT" },
  { id: 2260, name: "Tanaqob-Ouazzane", ref: "Tanaqob" },
  { id: 2161, name: "Tandit-outat elhaj", ref: "tnd" },
  { id: 289, name: "Tanger", ref: "TGR" },
  { id: 1742, name: "Tanougha-Beni Mellal", ref: "Tang" },
  { id: 1790, name: "TANTAN", ref: "TANT" },
  { id: 2044, name: "TAOUIMA-NADOR", ref: "TMAA" },
  { id: 1915, name: "taounate", ref: "taoun" },
  { id: 1874, name: "Taourirt", ref: "trt" },
  { id: 1835, name: "Tarfaya ville", ref: "tar" },
  { id: 1691, name: "targuist", ref: "tagu" },
  { id: 2221, name: "Tarmoucht-boumalne dades", ref: "trmch" },
  { id: 382, name: "Taroudant", ref: "TR" },
  { id: 2095, name: "Tassawt-kelaa des sraghna", ref: "tsswt" },
  { id: 1635, name: "Tassoultant-VILLE", ref: "Tassoul" },
  { id: 1696, name: "Tata", ref: "TTA" },
  { id: 2289, name: "tawarii- Sidi Yahya", ref: "tawarii" },
  { id: 808, name: "TAWJTAT", ref: "TWJT" },
  { id: 1872, name: "TAZA-VILLE", ref: "TZV" },
  { id: 1758, name: "Tazarine", ref: "Tarin" },
  { id: 2055, name: "tazmourt-taroudant", ref: "tzmrt" },
  { id: 1704, name: "Taznakht", ref: "Tazn" },
  { id: 1993, name: "TEMARA", ref: "TMRA" },
  { id: 2128, name: "temsamane-Driouch", ref: "tmsan" },
  { id: 1576, name: "Temsia-agadir", ref: "Tems" },
  { id: 2229, name: "Temsia(Ait Moussa)", ref: "Temsia" },
  { id: 1653, name: "Teroual - Ouazzane", ref: "Ter" },
  { id: 313, name: "Tetouan", ref: "TET" },
  { id: 1748, name: "Tidas-Khemisset", ref: "Tids" },
  { id: 1278, name: "Tiflet Ville", ref: "Tif" },
  { id: 2145, name: "Tifnit-agadir", ref: "tfnt" },
  { id: 1719, name: "Tighassaline ville", ref: "Tighas" },
  { id: 2207, name: "TIGHIRT-tiznit", ref: "tghrt" },
  { id: 2084, name: "TIGHMI-tiznit", ref: "TGHM" },
  { id: 1716, name: "Tikiouine", ref: "Tiki" },
  { id: 1721, name: "Timahdite", ref: "TMHD" },
  { id: 2281, name: "Timdline-ouarzazate", ref: "timdline" },
  { id: 2205, name: "TIMOLAY-guelmim", ref: "tml" },
  { id: 1740, name: "Timoulilt-Béni Mellal", ref: "Tim" },
  { id: 1582, name: "Tin Mansour", ref: "TiN" },
  { id: 2066, name: "Tindafel-assilah", ref: "tndfl" },
  { id: 1293, name: "Tinejdad Ville", ref: "Tine" },
  { id: 1475, name: "Tinghir ville", ref: "Tingi" },
  { id: 1907, name: "Tioughza", ref: "Tio" },
  { id: 1940, name: "tissa - taounate", ref: "tissa" },
  { id: 1698, name: "Tissint-tata", ref: "Tiss" },
  { id: 478, name: "TIT MELLIL", ref: "TTM" },
  { id: 1864, name: "tizi nisly-Beni Mellal", ref: "nisly" },
  { id: 1879, name: "Tizi Ousli", ref: "TZO" },
  { id: 376, name: "TIZNIT", ref: "TZ" },
  { id: 1976, name: "Tiztotine-DRIOUCH", ref: "TZTO" },
  { id: 2212, name: "Tkemast-tinghir", ref: "tkmst" },
  { id: 1592, name: "Tlat Bouaris", ref: "Bouari" },
  { id: 2074, name: "Tlat lghnimiyin-berrchid", ref: "ghnmit" },
  { id: 1738, name: "Tlat Loulad-fini", ref: "fini" },
  { id: 2257, name: "Tlensen-tantan", ref: "tlensen" },
  { id: 1947, name: "Tlet El Hanchane", ref: "hnch" },
  { id: 1591, name: "Tleta Bouguedra", ref: "Tleta" },
  { id: 1834, name: "Tnin beni khelloug-settat", ref: "tbkh" },
  { id: 1936, name: "tnin beni onjel - taounate", ref: "onjel" },
  { id: 1557, name: "TNIN EL GHIATE-SAFI", ref: "GHIATE" },
  { id: 2103, name: "Tnin jnan bih-chichaoua", ref: "tnnjnan" },
  { id: 1650, name: "Tnine Chtouka el jadida", ref: "Chto" },
  { id: 1590, name: "Tnine Gharbia", ref: "harbia" },
  { id: 1577, name: "tohmo agadir", ref: "tohm" },
  { id: 2049, name: "Toundout-OUARZAZET", ref: "tndt" },
  { id: 1963, name: "Tounfite-Midelt", ref: "Tunf" },
  { id: 2276, name: "Tskmoudin-tata", ref: " Tskmoudin" },
  { id: 2288, name: "twiza-Sidi Kacem", ref: "twiza" },
  { id: 2280, name: "Wad Lmalh-ouarzazate", ref: "wdmlh" },
  { id: 1960, name: "Wad lmarssa", ref: "wdmrs" },
  { id: 1957, name: "Wadalyane_ksar sghir", ref: "wd" },
  { id: 970, name: "Walidia", ref: "wld" },
  { id: 2086, name: "wargi-kelaa sraghna", ref: "wrgi" },
  { id: 1891, name: "wislan-meknes", ref: "wsln" },
  { id: 2009, name: "Wlad amer-ALAL TAZI", ref: "wldm" },
  { id: 1855, name: "Wlad Ghanem", ref: "Ghnem" },
  { id: 1887, name: "Wlad sidi yhya-meknes", ref: "sid" },
  { id: 1888, name: "wlad slim-meknes", ref: "slim" },
  { id: 1985, name: "Youssoufia-RABAT", ref: "YSSF" },
  { id: 2133, name: "youssoufia-ville", ref: "yssfia" },
  { id: 1829, name: "Zag-VILLE", ref: "VZag" },
  { id: 1033, name: "ZAGORA", ref: "ZGO" },
  { id: 1594, name: "Zaida", ref: "Zaida" },
  { id: 2217, name: "Zaouiat al bir-kelaa mgouna", ref: "zaouia" },
  { id: 1970, name: "Zaouiat Bougrine", ref: "ZBGR" },
  { id: 1047, name: "Zaouiat Cheikh", ref: "ZAKH" },
  { id: 2313, name: "Zaouiat nouaceurr-nouaceur", ref: "zaouiet" },
  { id: 1568, name: "Zaouit Sidi Smail", ref: "Zaouit" },
  { id: 1536, name: "zayou", ref: "DS" },
  { id: 1962, name: "ZGOUTA", ref: "ZGT" },
  { id: 2022, name: "Zouada-LAARACHE", ref: "zda" },
  { id: 1654, name: "Zoumi-Ouazzane", ref: "Zou" },
  { id: 1937, name: "zrizer - taounate", ref: "zrizer" },
];

export type CheckoutCity = { value: string; label: string; group?: string };

function cityGroup(name: string): string {
  // Keep checkout grouping aligned with admin metro rankings
  try {
    // lazy require avoided — duplicate light check
    const n = name.toLowerCase();
    if (n.includes("casablanca") || n.startsWith("casa ") || n === "casa") {
      return "Casablanca";
    }
    if (n.includes("marrakech") || n.includes("marrakesh")) return "Marrakech";
    if (n.includes("rabat")) return "Rabat";
    if (n.includes("tanger") || n.includes("tangier")) return "Tanger";
    if (n.includes("agadir")) return "Agadir";
  } catch {
    /* ignore */
  }
  return "Maroc";
}

/** Same names as OzonExpress (value = exact NAME for shipping). */
export const CHECKOUT_CITIES: CheckoutCity[] = OZONE_CITIES.map((c) => ({
  value: c.name,
  label: c.name,
  group: cityGroup(c.name),
}));

export function cityLabel(value: string): string {
  return value || "";
}

export function ozoneTrackingUrl(tracking: string): string {
  const tn = (tracking || "").trim();
  if (!tn || tn.startsWith("MAN-")) return "";
  return "https://ozonexpress.ma/#tracking";
}

export const STALE_SHIP_DAYS = 5;
